version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 15
  labels:
  - dependencies
  ignore:
  - dependency-name: electron
    versions:
    - "> 10.1.3"
    - "< 11"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a"
    - "< 14"
