dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: ng lint
    - stage: build
      if: branch = master
      script: npm run pack
    - stage: build
      if: branch != master
      script: npm run ng:build
