dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

before_deploy:
  - git config --global user.email "timon.gaebelein@icloud.com"
  - git config --global user.name "UnchartedBull"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

cache:
  directories:
    - ./node_modules

install:
  - npm install

jobs:
  include:
    - stage: lint
      script: ng lint
    - stage: build
      if: type = pull_request
      script: npm run ng:build
    - stage: build
      if: type = push
      script: npm run pack
    - stage: deploy
      if: type = push
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        draft: true
        file_glob: true
        file:
          - "**/package/*_arm64.deb"
          - "**/package/*_arm7vl.deb"
          - "**/package/*.dmg"
          - "**/package/*.exe"
